### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by My12123** [msxie92/MangaInpainting#13]
```python
(MangaInpainting) F:\MangaInpainting>python test.py --checkpoints ./checkpoints/mangainpaintor --input examples/test/imgs/ --mask examples/test/masks/ --line examples/test/lines/ --output examples/test/results/
Traceback (most recent call last):
  File "test.py", line 107, in <module>
    main()
  File "test.py", line 18, in main
    config = load_config(mode)
  File "test.py", line 86, in load_config
    config = Config(config_path)
  File "F:\MangaInpainting\src\config.py", line 8, in __init__
    self._dict = yaml.load(self._yaml)
TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by My12123** [comment]
pip install pyyaml==5.4.1
