### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by My12123** [msxie92/MangaInpainting#14]
```python
(MangaInpainting) F:\MangaInpainting>python test.py --checkpoints .\checkpoints\mangainpaintor --input .\examples\test\imgs\ --mask .\examples\test\masks\ --line .\examples\test\lines\ --output .\examples\test\results\
F:\MangaInpainting\src\config.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._dict = yaml.load(self._yaml)
Traceback (most recent call last):
  File "test.py", line 107, in <module>
    main()
  File "test.py", line 48, in main
    model = MangaInpaintor(config)
  File "F:\MangaInpainting\src\manga_inpaintor.py", line 17, in __init__
    self.semantic_inpaint_model = SemanticInpaintingModel(config).to(config.DEVICE)
  File "F:\MangaInpainting\src\models.py", line 50, in __init__
    generator = nn.DataParallel(generator, config.GPU)
  File "F:\1\envs\MangaInpainting\lib\site-packages\torch\nn\parallel\data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "F:\1\envs\MangaInpainting\lib\site-packages\torch\nn\parallel\data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "F:\1\envs\MangaInpainting\lib\site-packages\torch\nn\parallel\data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "F:\1\envs\MangaInpainting\lib\site-packages\torch\cuda\__init__.py", line 318, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

**Comment by magnum-fortyfive** [comment]
How did you solve this? The problem appears to be the program detecting more GPUs than ones that actually exist, and neither setting environment variables nor changing config.yml fixed this. Setting config.GPU to [0] in test.py stopped the error from showing up, but the program freezes after that point.
